# This workflow will do a clean installation of node dependencies, cache/restore them, run tests on node 16.x

name: Node.js CI

on:
  push:
    branches: 
    - "main"
  pull_request:
    branches: 
    - "main" 

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - run: npm ci
    
    - run: npm run build
    
    - run: npm run test:unit
    
  publish:
    needs: build
    if: ${{ success() }}
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/adviser-front-end -f ./Dockerfile ./adviser-front-end --no-cache

      - name: Docker Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}//adviser-front-end
   
