name: Main CD

on:
  schedule:
    - cron: '0 2 * * 2'
 
 

jobs:

  
  publish:
    
    if: ${{ github.event_name == 'schedule' && github.ref == 'refs/heads/main' && github.event.schedule }} && ${{ (github.event.repository.pushed_at | fromjson | strftime('%s') | int) > (now() - 604800 | int) }}
    
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout main branch
        uses: actions/checkout@v2  
        with: 
          ref: main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/adviser-front-end
