name: Main CD

# Runs CD every week on tuesday 2AM
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * 2'

jobs:
  publish:
    
    # Check if main updated in the last 7 days
    
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout main branch
        uses: actions/checkout@v2  
        with: 
          ref: main
          
      - name: Get last commit date on main branch
        id: main-branch
        run: echo "::set-output name=last_commit::$(git log -1 --format=%ct)"
        
      - name: Compare dates
        id: compare-dates
        run: |
          lastCommitDate=$(date -d @${{ steps.main-branch.outputs.last_commit }} +%Y-%m-%d)
          currentDate=$(date +%Y-%m-%d)
          sevenDaysAgo=$(date -d "$currentDate - 7 days" +%Y-%m-%d)
          if [[ $lastCommitDate > $sevenDaysAgo ]]; then
            echo "::set-output name=updated::true"
          else
            echo "::set-output name=updated::false"
          fi

      - name: Set up QEMU
        if: steps.compare-dates.outputs.updated == 'true'
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        if: steps.compare-dates.outputs.updated == 'true'
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        if: steps.compare-dates.outputs.updated == 'true'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push
        if: steps.compare-dates.outputs.updated == 'true'
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/adviser-front-end
